name: Build Jar

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Jar
        run: mvn clean package -DskipTests -Dspring.profiles.active=prod

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
